#!/bin/sh -e
# ============================================
#  splice_all - Controls the services splice depends on 
# ============================================
#
# :Usage: /etc/init.d/splice_all {start|stop|restart|status}
#

dropdatabase() {
    mongo 'checkin_service' --eval "db.dropDatabase();"
}

#
# Hack to force splice logging perms
# 
force_log_perms() {
    chown -R apache:splice /var/log/splice
    chown -R splice:splice /var/log/splice/celery
    chmod -R g+rw /var/log/splice
}

start() {
    force_log_perms
    service httpd start
    #service splice_celeryd start
    #service splice_celerybeat start
}

stop() {
    service httpd stop
    #service splice_celeryd stop
    #service splice_celerybeat stop
}

restart() {
    force_log_perms
    service httpd restart
    #service splice_celeryd restart
    #service splice_celerybeat stop
    #service splice_celerybeat start
}

status() {
    service httpd status
    #service splice_celeryd status
}

case "$1" in
    dropdatabase)
        dropdatabase
    ;;

    start)
        start
    ;;

    stop)
        stop
    ;;
    status)
        status
    ;;

    restart)
        restart
    ;;

    *)
        echo "Usage: /etc/init.d/splice_all {start|stop|restart|status}"
        exit 1
    ;;
esac

exit 0
