#!/bin/sh -e
# ============================================
#  splice_all - Controls the services splice depends on 
# ============================================
#
# :Usage: /etc/init.d/splice_all {start|stop|restart|status}
#

LOG_FILE=/var/log/splice/django.log

dropdatabase() {
    mongo 'checkin_service' --eval "db.dropDatabase();"
}

#
# Hack to force the django log file is writeable by apache
# 
force_log_perms() {
    if [ -f ${LOG_FILE} ] 
    then
        touch ${LOG_FILE}
    fi
    chown -R apache:apache ${LOG_FILE}
}

start() {
    force_log_perms
    service httpd start
    service splice_celeryd start
    service splice_celerybeat start
}

stop() {
    service httpd stop
    service splice_celeryd stop
    service splice_celerybeat stop
}

restart() {
    force_log_perms
    service httpd restart
    service splice_celeryd restart
    service splice_celerybeat stop
    service splice_celerybeat start
}

status() {
    service httpd status
    service splice_celeryd status
}

case "$1" in
    dropdatabase)
        dropdatabase
    ;;

    start)
        start
    ;;

    stop)
        stop
    ;;
    status)
        status
    ;;

    restart)
        restart
    ;;

    *)
        echo "Usage: /etc/init.d/splice_all {start|stop|restart|status}"
        exit 1
    ;;
esac

exit 0
